import todo as td
def test_add_todo():
    t = td.todo()
    t.add_todo("test1")
    t.add_todo("test2")
    data = t.get_data()
    print(len(data) == 2)
    print(data[0]["content"] == "test1")
    print(data[1]["content"] == "test2")
def test_category():
    t = td.todo()
    t.add_todo("test1")
    t.add_todo("test2")
    t.set_category("active")
    category_data = t.category_data()
    print(len(category_data) == 2)
    print(category_data[0]["content"] == "test1")
    print(category_data[1]["content"] == "test2")
    print(category_data[0]["category"] == "active")
    print(category_data[1]["category"] == "active")
def test_keyword():
    t = td.todo()
    t.add_todo("test1")
    t.add_todo("test2")
    t.set_keyword("1")
    keyword_data = t.keyword_data()
    print(len(keyword_data) == 1)
    print(keyword_data[0]["content"] == "test1")
def test_sort():
    t = td.todo()
    t.add_todo("test1")
    t.add_todo("test2")
    t.set_sort("content")
    sorted_data = t.sorted_data()
    print(len(sorted_data) == 2)
    print(sorted_data[0]["content"] == "test1")
    print(sorted_data[1]["content"] == "test2")
def test_view_data():
    t = td.todo()
    t.add_todo("test1")
    t.add_todo("test2")
    t.delete_data("2")
    view_data = t.view_data()
    print(view_data)

test_view_data()